math_nmn: &math_nmn
  model: NMN
  model_params:
    modules:
      "+": MLPModule(100, 4, 32, 2)
      "-": MLPModule(100, 4, 32, 2)
      "*": MLPModule(100, 4, 32, 2)
      "x": MLPModule(100, 2, 32, 2)
      "y": MLPModule(100, 2, 32, 2)
      "_output": MLPModule(100, 2, 32, 1)
  corpus: math
  train_size: med

math_lstm: &math_lstm
  model: LSTM
  model_params:
    batch_size: 100
    world_size: 2
    vocab_size: 7 # + - * x y ( )
    hidden_size: 32
    output_size: 1
  corpus: math
  train_size: med

experiment: *math_lstm
