math_nmn: &math_nmn
  model: NMN
  input_type: VectorInput()
  output_type: SquaredError()
  model_params:
    modules:
      "+": MLPModule(100, 4, 32, 2)
      "-": MLPModule(100, 4, 32, 2)
      "*": MLPModule(100, 4, 32, 2)
      "x": MLPModule(100, 2, 32, 2)
      "y": MLPModule(100, 2, 32, 2)
      "_output": MLPModule(100, 2, 32, 1)
  corpus: math
  train_size: med

math_lstm: &math_lstm
  model: LSTM
  model_params:
    batch_size: 100
    world_size: 2
    vocab_size: 7
    hidden_size: 32
    output_size: 1
  corpus: math
  train_size: large

shapes_nmn: &shapes_nmn
  model: NMN
  input_type: ImageInput()
  output_type: Classification()
  batch_size: 64
  model_params:
    module_builder: 
      class: ShapesModuleBuilder
      batch_size: 64
      image_size: 30
      channels: 3 
      mid_filters: 8
      out_filters: 1
      input_mid_filter_size: 5
      input_out_filter_size: 3
      filter_size: 3
      input_mid_pool: 5
      input_out_pool: 2
      hidden_size: 8
      vocab_size: 2

  corpus: shapes
  train_size: large

images_nmn: &images_nmn
  model: NMN
  input_type: ImageInput()
  output_type: Classification()
  model_params:
    module_builder:
      class: ImagesModuleBuilder
      channels: 256
      vocab_size: 380

  corpus: images
  train_size: large

shapes_lstm: &shapes_lstm
  model: LSTM
  input_type: ImageInput()
  output_type: Classification()
  model_params:
    batch_size: 64
    #world_size: 900
    image_size: 30
    channels: 3
    vocab_size: 14
    hidden_size: 8
    output_size: 2
    query_max_length: 10

  corpus: shapes
  train_size: large

experiment: *images_nmn
