task:
  name: cocoqa
  pad_to_width: 20
  pad_to_height: 20

model:
  name: nmn
  include_reading_module: false
  hidden_size: 500
  image_features: 64
  #load_lstm: "saves/daquar_lstm_135.h5"

opt:
  batch_size: 64
  batch_by: layout
  learning_rate: 0.001
  momentum: 0.9
  clip: 10
  iters: 1001
