task:
  name: daquar
  train_size: reduced
  pad_to_width: 20
  pad_to_height: 20

model:
  name: nmn
  include_reading_module: false
  hidden_size: 16

opt:
  batch_size: 64
  learning_rate: 0.01
  momentum: 0.9
  clip: 1
  iters: 1001
