corpus:
  name: images
  train_size: large

model:
  name: lstm
  question_mode: query
  hidden_size: 32
  image_before: true
  image_after: true
  #layer_builder:
  #  name: images
  #  embedding_path: data/embeddings/skipdep_lc


opt:
  batch_size: 128
  learning_rate: 0.0001
  momentum: 0.9
  clip: 1
  #epsilon: 0.000001
  #rho: 0.95
  #lr: 0.1
  #clip: 1
  iters: 1001
