task:
  name: images
  train_size: small
  pad_to_width: 20
  pad_to_height: 20

model:
  name: nmn
  include_reading_module: false
  hidden_size: 32

opt:
  batch_size: 1
  learning_rate: 0.001
  momentum: 0.9
  clip: 1
  iters: 10001
