backend: caffe

corpus:
  name: images
  train_size: large

model:
  name: nmn
  module_builder:
    name: images
    input_size: 256
    hidden_size: 32

opt:
  batch_size: 64
  learning_rate: 0.01
  momentum: 0.9
  clip: 1
  iters: 100
